version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  extension:
    description: 'Unit tests for Node app'
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  # web:
  #   description: 'Frontend tests for Web app'
  #   executor:
  #     name: node/default
  #   environment:
  #     SKIP_PREFLIGHT_CHECK: true
  #     REACT_APP_TUTORIAL_LIST_URL: https://raw.githubusercontent.com/coderoad/tutorials/master/tutorials.json
  #   working_directory: ~/web-app
  #   steps:
  #     - checkout
  #     - node/with-cache:
  #         steps:
  #           - run: cd web-app && npm install
  #           - run: cd web-app && npm test

workflows:
  build-and-test:
    jobs:
      - extension
      # - web
      # - e2e
      # - package
